### ISSUE TITLE
shorthand CSS rules

### ISSUE THREAD

**Issue by fcsonline** [keithclark/selectivizr#10]
Hello,

first of all thanks for this great tool.

Yesterday, I was testing selectivizr and I found a problem with the shorthand declarations. I have been trying to reduce the usecase to minimum:

-- reset.css -- 

<pre>
table, tr, td {
    background: transparent;
}
</pre>

-- end reset.css --

-- style.css -- 

<pre>
tr:nth-child(odd){
    background-color: rgb(0,255,0);
}

tr:nth-child(even){
    background-color: rgb(0,155,0);
}
</pre>

-- end style.css -- 

-- index.html -- 

<pre>
&lt;!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
&lt;html xmlns="http://www.w3.org/1999/xhtml" lang="es">
    &lt;head>
        &lt;title>Selectivizr Test</title>
        &lt;meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
        &lt;link rel="stylesheet" type="text/css" href="css/reset.css" media="screen"/>
        &lt;link rel="stylesheet" type="text/css" href="css/style.css" media="screen"/>

        &lt;script type="text/javascript" src="js/jquery-1.4.3.min.js"></script>

        &lt;!--[if (gte IE 6)&(lte IE 8)]>
        &lt;script type="text/javascript" src="js/selectivizr.js">&lt;/script>
        &lt;![endif]-->

    &lt;/head>
    &lt;body>
        &lt;table border="0">
            &lt;tbody>
                &lt;tr>&lt;td>Col1&lt;/td>&lt;td>Col2&lt;/td>&lt;/tr>
                &lt;tr>&lt;td>Col1&lt;/td>&lt;td>Col2&lt;/td>&lt;/tr>
                &lt;tr>&lt;td>Col1&lt;/td>&lt;td>Col2&lt;/td>&lt;/tr>
            &lt;/tbody>
        &lt;/table>
   &lt;/body>
&lt;/html>
</pre>

-- end index.html -- 

I tested the usecase in a Internet Explorer 7 vs. Firefox 4 and in the first one, the table is white and the second  is green.

Do you know anything about it?

See you,

**Comment by keithclark** [comment]
I'm not aware of any issues related to shorthand declarations (by that, I'm assuming you mean `table, tr, td {...}`) but I'll recreate your test and feedback with my findings.

**Comment by keithclark** [comment]
I managed to recreated your issue and I've done a little reading. It looks like `background: transparent` in IE7 is buggy (now there's a surprise!). If you remove that rule from reset.css (or replace it with another) everything works just fine.

**Comment by fcsonline** [comment]
Oh, sorry. I did not know this 'behavior' of Internet Explorer.

I will modify the css according to your comment.

Thank you! ;)
