### ISSUE TITLE
CSS selector engine management

### ISSUE THREAD

**Issue by pyrsmk** [keithclark/selectivizr#12]
Hi,

I think you could consider to add a function to specify the CSS selecting function. Then, we could plug in less-used libs like qwery.

What do you think about that?

**Comment by keithclark** [comment]
I have plans for a selectivizr global object and to add a selectorMethod property to allow developers to wire in their own choice of selector engine.

**Comment by pyrsmk** [comment]
Nice, this will be awesome :) I let it opened until that future release.

**Comment by barneycarroll** [comment]
Does Selectivizr currently expose anything to the global context? I'm trying to do the HTML5 boilerplate trick of pulling it in from cdnjs.com and falling back to a local copy if it's not available…

**Comment by pyrsmk** [comment]
Since the project is clearly unmaintained, I'm closing the issue.
