### ISSUE TITLE
IE version regex isn't IE10 proof

### ISSUE THREAD

**Issue by paulirish** [keithclark/selectivizr#2]
```
var ieVersion = /MSIE ([\d])/.exec(navigator.userAgent)[1];
```

you're gonna want a `+` after that `\d`

Now this bug doesnt really affect anything since you discard IE before 6 and after 8 (until we hit IE version 60...)

but it's good to have this fixed in case someone else snags that code for their own use.

**Comment by keithclark** [comment]
Good point.

**Comment by keithclark** [comment]
Fixed regex in this commit:

https://github.com/keithclark/selectivizr/commit/56335f4f1610c639625db14d1c1293aaf378e748
