### ISSUE TITLE
explore other (non-doc.write) dom ready solutions

### ISSUE THREAD

**Issue by paulirish** [keithclark/selectivizr#3]
this old dean edwards snippet was used in jquery but was removed due to edge case incompatibilities.

the doScroll basic check from diego perini (called IEContentLoaded) is much safer.

**Comment by keithclark** [comment]
I agree, document.write isn't the best way to watch for DOM ready events.

Originally, I used Diego's doScroll() trick but it failed if selectivizr was used in any content loaded into an iframe, so I had to revert back to Dean Edwards technique as it was causing issues for some users.

I'm open to suggestions.

**Comment by paulirish** [comment]
Ah interesting.  I'll tweak the issue title.

**Comment by ZeeAgency** [comment]
https://github.com/keithclark/selectivizr/pull/6

**Comment by keithclark** [comment]
Diego has been in touch.

I have a new version of his DOMContentLoaded script to test :)

**Comment by keithclark** [comment]
Closing this issue as it's become a dupe of issue #4
