### ISSUE TITLE
ability to lazyload in selectivizr

### ISSUE THREAD

**Issue by paulirish** [keithclark/selectivizr#4]
I'd like to load selectivizr.js into the page only if I'm in a browser that I'll need it.

this is related to issue #3. as `document.write` will blow up attempts to lazy load scripts.

the trick is selectivizr.js might load before or after "dom ready" .. so we'll need to watch the `document.readyState` instead of waiting for events to fire (that already did).  i think..

**Comment by paulirish** [comment]
ps. thanks for being on github!!! :) i very much enjoyed reading through the source.

**Comment by ZeeAgency** [comment]
https://github.com/keithclark/selectivizr/pull/6

I join Paul : thx for putting the source on github :-)

**Comment by keithclark** [comment]
I've updated the script to include Diego Perini's new ContentLoaded method which appears to solve this issue.

It would be great if you could test it in a live environment.

**Comment by keithclark** [comment]
Closed
