### ISSUE TITLE
Still alive?

### ISSUE THREAD

**Issue by linjunpop** [keithclark/selectivizr#40]
Is this project a dead one?

Last update is a year ago?

**Comment by minchal** [comment]
@keithclark can you upload minified file from git version? I really need this fix for CSS3PIE :)

Version from git works fine, but i can't put unminified file on production.

**Comment by phillip-haydon** [comment]
Looks like another dead project :(

**Comment by keithclark** [comment]
You can now minify selectivizr.js yourself using your tool of choice.
