### ISSUE TITLE
Error in IE8 when there is "input:focus:invalid" in css

### ISSUE THREAD

**Issue by PG-kura** [keithclark/selectivizr#60]
To "Twitter Bootstrap 2.3.1" contains the css like this.

<pre>
input:focus:invalid,
textarea:focus:invalid,
select:focus:invalid {
  color: #b94a48;
  border-color: #ee5f5b;
}
</pre>

Error dialog similar to the following is displayed in IE8 using both selectivizr.js above.

![invalid error](https://f.cloud.github.com/assets/480014/360326/37978e6c-a18d-11e2-9f93-c26560e60663.png)

**Comment by benjamincharity** [comment]
I don't believe that IE8 supports multiple pseudo classes. Also, Selectivizr adds CSS selector support to various Javascript libraries...not the browser itself. So the above CSS will still throw an error, but you would be able to use the selectors within your Javascript: eg `$('div:last-child')...`

**Comment by PG-kura** [comment]
All right. Thank you.
